### PR TITLE
Add staffers from The Dallas Morning News.

### PR DESCRIPTION
**Pull request by allanjamesvestal**
My Atom config automatically deletes trailing spaces from a few dozen lines whenever I save. Hope that's not terribly inconvenient for anyone.

### CODE REVIEW

**Comment by lisacharlotterost** [comment]
Thanks for adding all these names! If this list would be about all news nerds, we're likely to end up with something like this: https://source.opennews.org/en-US/organizations/dallas-morning-news/ 
I'm really more looking for people who work on graphics. Could you select just the people who create them, no matter in which department? 

And if everybody on these two teams creates graphics, can you please create two different teams for them (including links to Twitter / Github etc.)? 

Thank you!

**Comment by allanjamesvestal** [comment]
Lisa — 

Thanks for the quick response, and for creating this repo. It'll definitely be a useful tool to have!

I'm curious what sort of graphics workers you're looking for. In our newsroom, as in many I've seen, graphics isn't a single, finite desk anymore — it's a collective responsibility.

At _The News_, we have two teams that produce these types of content — our interactives editors (who create frontend-heavy special presentations and some datavis) and our computational journalists (who make more complex data visualizations, build public- and newsroom-facing apps and analyze data).

None of our team members report through a centralized graphics department — or have traditional graphics work as their sole responsibility — but the seven I added are the ones who regularly create graphics as part of their body of work. I tried to use the listed members from other larger organizations as a guide, as it appears you have a mix of more datavis and frontend-focused people (like Sarah Almukhtar of the NYT) and more systems and backend-focused people (like Jeremy Bowers, also of the NYT). (That said, I was careful to exclude others who didn't seem to have their counterparts from other organizations listed here — such as staff illustrators, print-specific graphic artists or the half-dozen reporters who use some form of SQL regularly in covering their beats.)

Please let me know if you have any questions about our teams and the work they do, or if you'd like me to revise this list to add or remove anyone.

**Comment by lisacharlotterost** [comment]
Hi Allan, 

thanks for your detailed explanation! This list is one big experiment, and I'm happy to see it already failing: Because that means that graphics become more and more important outside of a "core department". Thanks for pointing that out! I think it would be best to just gather all the people under one newsroom name who do data vis, no matter in which department there are in. In your case, I will just delete the name of the departments. And I will rewrite the intro text a bit.

The original idea was to focus on HOW a team works; that's why I started to include links to talks and blog posts. I guess that the difference in tools and methods within a newsroom differs as much or more than across all newsrooms (meaning, it depends more on the person than on the newsroom); but every newsroom also has their specific tools and principles I'm curious about. If you could add a link to a blogpost or talk in which one of you talks about yours, that would be great! 

And I need to admit that the list of NYT people is indeed too long. I'll remove Jeremy Bowers and some other great people who have little to do with data vis in their daily lives (or people I'm not sure about).

Thanks again!

**Comment by lisacharlotterost** [comment]
added them. Thanks again!

**Pull request closed without merging**
